// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build loong32r

#include "textflag.h"

// Set the C function pointer used by pthread teardown to the local trampoline.
TEXT ·set_crosscall2(SB),NOSPLIT,$0-0
	MOVW	_crosscall2_ptr(SB), R5
	MOVW	$crosscall2_trampoline<>(SB), R6
	MOVW	R6, (R5)
	RET

TEXT crosscall2_trampoline<>(SB),NOSPLIT,$0-0
	JMP	crosscall2(SB)

// Called by C code generated by cmd/cgo.
// func crosscall2(fn, a unsafe.Pointer, n int32, ctxt uintptr)
//
// C arguments arrive in R4-R7. The Go ABI0 frame needs fn, a, and ctxt at
// 4(SP), 8(SP), and 12(SP); n in R6 is intentionally omitted. Preserve the
// complete LA32 ILP32S integer callee-save set. The target is soft-float.
TEXT crosscall2(SB),NOSPLIT|NOFRAME,$0
	ADD	$-64, R3
	MOVW	R4, 4(R3)
	MOVW	R5, 8(R3)
	MOVW	R7, 12(R3)
	MOVW	g, 16(R3)
	MOVW	R23, 20(R3)
	MOVW	R24, 24(R3)
	MOVW	R25, 28(R3)
	MOVW	R26, 32(R3)
	MOVW	R27, 36(R3)
	MOVW	R28, 40(R3)
	MOVW	R29, 44(R3)
	MOVW	R30, 48(R3)
	MOVW	R31, 52(R3)
	MOVW	R1, 56(R3)

	CALL	runtime·load_g(SB)
	CALL	runtime·cgocallback(SB)

	MOVW	16(R3), g
	MOVW	20(R3), R23
	MOVW	24(R3), R24
	MOVW	28(R3), R25
	MOVW	32(R3), R26
	MOVW	36(R3), R27
	MOVW	40(R3), R28
	MOVW	44(R3), R29
	MOVW	48(R3), R30
	MOVW	52(R3), R31
	MOVW	56(R3), R1
	ADD	$64, R3
	RET
